site_name: RsR Docs
nav:
  - Home: index.md
  - Usage: usage.md
  - 3rd page: 3rd_page.md

theme:
  name: material
  palette: 
    primary: indigo
    accent: red
  features:
    - navigation.instant
    - header.autohide